# Generated by Django 6.0.3 on 2026-03-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, default='articles/default.png', upload_to='articles/'),
        ),
    ]
