# Generated by Django 6.0.3 on 2026-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, height_field='700px', upload_to='images', width_field='700px'),
        ),
    ]
