# Generated by Django 6.0.3 on 2026-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
