# Generated by Django 6.0.3 on 2026-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='post.hashtag', verbose_name='Хэштеги'),
        ),
    ]
