# Generated by Django 6.0.3 on 2026-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_comments_article_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Хэштег', 'verbose_name_plural': 'Хэштеги'},
        ),
    ]
