# Generated by Django 6.0.3 on 2026-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_article_title_en_article_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category_Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category_Name'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
